using System;
using System.Security.Cryptography;
using System.IO;
using System.Text;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using Newtonsoft.Json;

/// dotnet run -- 4 ..\output ..\croplist.json

namespace csharp {
    class Program {
        static void Main(string[] args) {
            if (args.Length < 3) {
                Console.WriteLine("Invalid arguments. Please input the scale multiplier, followed by a base filename (without extension) and the folder containing the output of textureAtlas-slicer. the [basefilename]_sliced.png (generated by textureAtlas-slicer) as well as [basefilename].json should exists at the path specified");
                Console.WriteLine("Example arguments: 4 ..\\tex1_512x256_B20814E2D6573DFE_0 ..\\output");
                return;
            }

            var multiplier = int.Parse(args[0]); // throws ¯\_(ツ)_/¯
            if (multiplier <= 0) {
                Console.WriteLine("Invalid multiplier. Please use integer values");
                return;
            }

            var texturePath = $"{args[1]}_sliced.png";
            if (File.Exists(texturePath) == false) { Console.WriteLine($"Invalid filename. {texturePath} missing"); return; }
            var texture = Image.Load(texturePath); // throws ¯\_(ツ)_/¯
            
            var parametersPath = $"{args[1]}.json";
            if (File.Exists(parametersPath) == false) { Console.WriteLine($"Invalid filename. {parametersPath} missing"); return; }
            var parametersString = File.ReadAllText(parametersPath); // throws ¯\_(ツ)_/¯
            var parameters = JsonConvert.DeserializeObject<Rectangle[]>(parametersString);
            
            foreach (var parameter in parameters) {
                var upscaledImagePath = $"{args[2]}\\{GetSimpleFilename(parameter)}.png";
                var upscaledImage = Image.Load(upscaledImagePath);
                var upscaledImageLocation = new Point(multiplier * parameter.X, multiplier * parameter.Y);
                texture.Mutate(context => context.DrawImage(
                    upscaledImage,
                    upscaledImageLocation,
                    SixLabors.ImageSharp.PixelFormats.PixelColorBlendingMode.Normal,
                    SixLabors.ImageSharp.PixelFormats.PixelAlphaCompositionMode.SrcOver,
                    1.0f));
            }
            texture.SaveAsPng($"{args[1]}_final.png");
        }
        public static string GetSimpleFilename(Rectangle rectangle) { 
            return rectangle.X.ToString() + "-" + rectangle.Y.ToString() + "-" + rectangle.Width.ToString() + "-" + rectangle.Height.ToString();
        }

        public static string GetHashString(Rectangle rectangle) {
            var parameterString = JsonConvert.SerializeObject(rectangle);
            var parameterBytes = Encoding.UTF8.GetBytes(parameterString);
            HashAlgorithm algorithm = SHA256.Create();
            var resultBytes = algorithm.ComputeHash(parameterBytes);
            StringBuilder sb = new StringBuilder();
            foreach (byte b in resultBytes) {
                sb.Append(b.ToString("x"));
            }
            return sb.ToString();
        }
    }
}
